language: haskell
ghc: 7.8
install:
  # Happy needs to be updated for haskell-src: https://github.com/haskell-suite/haskell-src-exts/issues/64
  - cabal install happy
  - cabal install --only-dependencies --enable-tests